### ISSUE TITLE
Python 3.12 JPype1 installation error

### ISSUE THREAD

**Issue by LewisSarcasm** [clearbluejar/ghidriff#53]
There is an issue with python 3.12 not correctly installing Ghidriff. 

The issue lies with JPype1 not being correctly installed using PIP. 

Changing to python 3.10 works for. Perhaps add this into the README section, that the user should not use python 3.12 (maybe 3.11 too). 

Within the setup.cfg file there is no mention of any version above 3.10:
```
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
```

**Comment by clearbluejar** [comment]
Ah thanks for that. Yeah there are recent [build issues](https://github.com/jpype-project/jpype/issues/1147) with `jpype` on Python 3.12.  I have even updated my automated testing until the fix is in. 

https://github.com/clearbluejar/ghidriff/commit/b9b17db182fc435d38cce5e3dff5103bdd9954be#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686

I will update the setup.cfg to include up to 3.11 for now, until the 3.12 jpype issue is solved. 

I will keep this ticket open until the `jpype` fix is in.

**Comment by clearbluejar** [comment]
Some awesome progress has been made here: https://github.com/jpype-project/jpype/issues/1162 . I will push a new version to support 3.12 when available.
